language: node_js
sudo: true
node_js:
  - "8"
dist: trusty
before_install: if [[ `npm -v` < 3 ]]; then npm i -g npm@latest; fi
before_script:
  - npm install -g grunt-cli
  - chmod 777 ./setup/redis/travis-redis.sh
  - ./setup/redis/travis-redis.sh
  - grunt css
addons:
  apt:
    packages:
      - google-chrome-stable
services:
  - redis-server
before_deploy:
  - sh ./tools/release.sh
deploy:
  provider: releases
  api_key:
    secure: W3nIzaD4My6ePIMS7rOjA8FIDCY8UokHQGmWhcFsuh2KssfYHlKNsadyPWWOOTxgEVUhOrOMprLTNLzBHxVt0VpuKUgie4+G8X2CMwhLj1wSLTPRVB3eeMJAyUMAPlhBVxuu56LdZQFSbXJDyKCBO9yBYpbo70SVUsIwMRtkasQ=
  file_glob: true
  file: ../enketo-express-packages/*.zip
  on:
    tags: true
    condition: $TRAVIS_TAG =~ \.oc-
    repo: OpenClinica/enketo-express-oc
    node: 8
    all_branches: true 
